export const GET_LIFEREVIEW_START = 'GET_LIFEREVIEW_START'
export const GET_LIFEREVIEW_SUCCESS = 'GET_LIFEREVIEW_SUCCESS'
export const GET_LIFEREVIEW_FAILED = 'GET_LIFEREVIEW_FAILED'

export const GET_MESSAGES_START = 'GET_MESSAGES_START'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED'

export const CREATE_MESSAGE_START = 'CREATE_MESSAGE_START'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAILED = 'CREATE_MESSAGE_FAILED'

